### ISSUE TITLE
better error message when I forget "add"?

### ISSUE THREAD

**Issue by jessitron** [johnwalker/lein-plz#13]
When I type "lein plz <library>" I get an error message that suggests I file a bug report.
This prevented me from using the library the first time I tried it; I thought it didn't work.

Maybe say "I don't know how to <library>, maybe try 'add' or 'list'?"

this is what I see now:

    jessitron$ cd elastic_search/event-monitor/
    event-monitor jessitron$ lein plz schema
    Format specifier '%s'
    File a bug report here:
    https://github.com/johnwalker/lein-plz
    --
    nil

**Comment by johnwalker** [comment]
I agree. I'll accept a PR that catches this

**Comment by johnwalker** [comment]
Err yeah, sorry about that. When you get a chance, try 0.3.1-SNAPSHOT and let me know if it works as you expect it. Should do something like:

```
~/development/lein-plz $ lein plz
Add dependencies to your existing project.clj file.
Use the following commands:

  - add <nick or nicks> -- Adds the dependencies associated with each nick to the project.
    Example: lein plz add core.async cljs data.json

  - list <& filter> -- List the built-in (total 449) dependencies with their nicknames.
    If called with a filter, it will be passed as a regular expression to limit the amount of entries.
    Example: lein plz list org.clojure/
```

**Comment by jessitron** [comment]
It looks great! Thank you.

**Comment by johnwalker** [comment]
Cool, I'll push 0.3.1 this weekend and will keep this issue open in the meantime. Thanks for your report.

**Comment by jessitron** [comment]
Thanks for your plugin!

**Comment by johnwalker** [comment]
You're welcome! It's out. Let me know if anything else pops up, or if you have other ideas for the plugin.
